#!/bin/bash

# ============================================
# QUICK SETUP GUIDE
# BOC-LINK CI/CD with GitLab + Docker + VPS
# ============================================

echo "📋 QUICK SETUP GUIDE - BOC-LINK CI/CD"
echo ""
echo "⏱️  Time needed: ~10 minutes"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""

echo "STEP 1️⃣  - Login to VPS"
echo "────────────────────────────────────────────────────────"
echo "ssh root@your-vps-ip"
echo ""
echo "Or copy this:"
echo "ssh root@160.191.87.43"
echo ""

echo "STEP 2️⃣  - Download & run VPS setup"
echo "────────────────────────────────────────────────────────"
echo "curl -O https://your-gitlab-url/setup-vps-auto.sh"
echo "bash setup-vps-auto.sh"
echo ""
echo "(Watch for any errors - all should pass)"
echo ""

echo "STEP 3️⃣  - Create Deploy Key"
echo "────────────────────────────────────────────────────────"
echo "bash setup-deploy-key.sh"
echo ""
echo "Copy the SSH PUBLIC KEY output (starts with ssh-rsa)"
echo ""

echo "STEP 4️⃣  - Add Deploy Key to GitLab"
echo "────────────────────────────────────────────────────────"
echo "1. Go to: Your Project → Settings → Deploy keys"
echo "2. Click: 'Add new key'"
echo "3. Name: 'boc-link-vps'"
echo "4. Paste the SSH public key from STEP 3"
echo "5. ✅ CHECK: 'Grant write access'"
echo "6. Click: 'Add key'"
echo ""

echo "STEP 5️⃣  - Add CI/CD Variables to GitLab"
echo "────────────────────────────────────────────────────────"
echo "Go to: Your Project → Settings → CI/CD → Variables"
echo ""
echo "Add these variables (from your .env):"
echo ""
echo "Protected = ✓, Masked = depends on value"
echo ""
echo "  NEXTAUTH_URL               (your app URL)"
echo "  NEXTAUTH_SECRET            (secret key)"
echo "  DB_ROOT_PASSWORD"
echo "  DB_NAME                    (boclink)"
echo "  DB_USER                    (boclink_user)"
echo "  DB_PASSWORD"
echo "  DATABASE_URL               (full connection string)"
echo "  DOCKER_IMAGE_NAME          (boc-link)"
echo "  DOCKER_USERNAME            (your Docker Hub username)"
echo "  DOCKER_PASSWORD            (Docker Hub token)"
echo "  VPS_HOST                   (your VPS IP)"
echo "  VPS_USER                   (root)"
echo "  SSH_PRIVATE_KEY            (your SSH private key)"
echo ""

echo "STEP 6️⃣  - Test CI/CD"
echo "────────────────────────────────────────────────────────"
echo "git add ."
echo "git commit -m 'feat: CI/CD setup'"
echo "git push origin main"
echo ""
echo "Then go to: GitLab → Build → Pipelines"
echo "Watch the build & deploy jobs"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "✨ DONE!"
echo ""
echo "Next: CODE → PUSH → AUTO DEPLOY 🚀"
echo ""
echo "═══════════════════════════════════════════════════════"
